# Generated by Django 5.0.4 on 2024-05-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Diseño', 'Diseño')], max_length=100),
        ),
    ]
